apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: notes-frontend
  ports:
    - protocol: TCP
      port: 80       # Service port
      targetPort: 80 # Container port (Nginx)
      nodePort: 30080 # External port (you can change this)
