name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  dockerize-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Bandit Security Scan
        run: |
          pip install bandit
          bandit frontend/apiserver.py -f html -o bandit-report-backend.html || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report-backend
          path: bandit-report-backend.html

      - name: Change to workdir
        working-directory: ./backend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-backend:latest


  dockerize-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change to workdir
        working-directory: ./frontend
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-frontend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/code-analyzer-frontend:latest

  k8s-yaml-deploy:
    runs-on: self-hosted
    needs:
      - dockerize-backend
      - dockerize-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/ -n code-analyzer

      - name: Restart Kubernetes api-resources
        run: kubectl rollout restart deployment,statefulset -n code-analyzer